### ISSUE TITLE
Rebase Integration Strategy

### ISSUE THREAD

**Issue by benjaminclark964** [benjaminclark964/CS471WorkflowsHomeworkAssignment#3]
References user story #1

## TODO:
- [x] Create a new PR having the **base** branch `master` and the **compare** branch `task-3_rebase`
- [x] Edit the description of the PR to reference this task
- [x] Understand the commits and changes made to the PR
- [x] In the PR, use the `Rebase and merge` option to integrate the changes into `master`
- [x] Use the GitHub interface to delete the branch of the PR after successfully integrating it into `master`
