### ISSUE TITLE
Squash with Default Message Integration Strategy

### ISSUE THREAD

**Issue by benjaminclark964** [benjaminclark964/CS471WorkflowsHomeworkAssignment#4]
References user story #1

## TODO:
- [x] Create a new PR having the **base** branch `master` and the **compare** branch `task-4_squash`
- [x] Edit the description of the PR to reference this task
- [x] Understand the commits and changes made to the PR
- [x] In the PR, use the `Squash and merge` option to integrate the changes into `master` and the commit message should be the **default** one provided by GitHub (e.g., `Task 4 squash (#<ID_PR>)`), and do not make any changes to it
- [x] Use the GitHub interface to delete the branch of the PR after successfully integrating it into `master`
